name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: ':sparkles: MOD更新'
    labels: [ 'mod','core' ]
  - title: ':sparkles: 内容包'
    labels: [ 'contents' ]
  - title: ':wrench: 洪水模式 Flood'
    labels: [ 'contents:flood' ]
autolabeler:
  - label: 'core'
    files:
      - 'core/**'
  - label: 'contents:flood'
    files:
      - 'contents/flood.json'
  - label: 'contents'
    files:
      - 'contents/**'
  - label: 'mod'
    files:
      - 'loaderMod/**'
change-template: |
  - $TITLE @$AUTHOR (#$NUMBER)
    $BODY
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  # 更新内容
  $CHANGES