name: Build

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build MOD
        run: |
          export VERSION="beta-$GITHUB_RUN_NUMBER"
          ./gradlew dist
      - name: Upload MOD JAR
        uses: actions/upload-artifact@v2
        with:
          path: build/dist/*