name: Build

on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2             # fetch the whole repo history
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: build MOD
        run: ./gradlew dist
      - name: Upload MOD JAR
        uses: actions/upload-artifact@v2
        with:
          path: loaderMod/build/dist/*

      - uses: release-drafter/release-drafter@v5
        if: github.ref_name == 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}